/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// GAME_URLS.json
var require_GAME_URLS = __commonJS({
  "GAME_URLS.json"(exports, module2) {
    module2.exports = {
      DOOM: "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/doom.jsdos?anonymous=1",
      "DOOM II": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/doom2.jsdos?anonymous=1",
      "WOLFENSTEIN 3D": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/a/ac888d1660aa253f0ed53bd6c962c894125aaa19.jsdos?anonymous=1",
      HERETIC: "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/heretic.jsdos?anonymous=1",
      "PRINCE OF PERSIA": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/1/1179a7c9e05b1679333ed6db08e7884f6e86c155.jsdos?anonymous=1",
      "MORTAL COMBAT": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/8/872f3668c36085d0b1ace46872145285364ee628.jsdos?anonymous=1",
      GTA: "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/gta-mobile.jsdos?anonymous=1",
      "SIM CITY": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/7/744842062905f72648a4d492ccc2526d039b3702.jsdos?anonymous=1",
      "NEED FOR SPEED": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/nfs.jsdos?anonymous=1",
      "TYRIAN 2000": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/custom/dos/tyrian-2000.jsdos?anonymous=1",
      "THE LOST VIKINGS": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/1/1b063b2520052ebb504184667ac95e72423331de.jsdos?anonymous=1",
      "OUT OF THIS WORLD": "https://dos.zone/player/?bundleUrl=https://cdn.dos.zone/original/2X/1/1031eb810e8b648fc5f777b3bd9cbc0187927fd4.jsdos?anonymous=1"
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsiDOOM
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/SidePanel.ts
var import_obsidian = require("obsidian");
var SIDE_PANEL_ID = "obsidoom";
var GAME_URLS = require_GAME_URLS();
var SidePanel = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.endGameButton = document.createElement("button");
    this.openGameButton = document.createElement("button");
    this.gameSelect = document.createElement("select");
    this.gameDiv = document.createElement("div");
    this.dropDownDiv = document.createElement("div");
    this.endGameButton = document.createElement("button");
    this.endGameButton.addClass("doom-button");
    this.endGameButton.setText("Close Game");
    this.endGameButton.onClickEvent(() => {
      var _a;
      this.disableButton(this.endGameButton);
      (_a = this.gameDiv.firstChild) == null ? void 0 : _a.remove();
      this.enableButton(this.openGameButton);
    });
    this.openGameButton = document.createElement("button");
    this.openGameButton.addClass("doom-button");
    this.openGameButton.setText("Open Game");
    this.openGameButton.onClickEvent(() => {
      this.disableButton(this.openGameButton);
      this.gameDiv.appendChild(this.generateGameIFrame(this.gameSelect.value));
      this.enableButton(this.endGameButton);
    });
    this.dropDownDiv.addClass("doom-dropdown");
    const label = document.createElement("label");
    label.setText("Select Game:");
    this.gameSelect.id = "game-select";
    this.gameSelect.name = "game-select";
    for (const game in GAME_URLS) {
      const option = document.createElement("option");
      option.value = game;
      option.text = game;
      this.gameSelect.appendChild(option);
    }
    this.gameSelect.onchange = (_) => {
      var _a;
      (_a = this.gameDiv.firstChild) == null ? void 0 : _a.remove();
      this.disableButton(this.openGameButton);
      this.gameDiv.appendChild(this.generateGameIFrame(this.gameSelect.value));
      this.enableButton(this.endGameButton);
    };
    this.dropDownDiv.appendChild(label);
    this.dropDownDiv.appendChild(this.gameSelect);
  }
  static async activate(workspace) {
    var _a;
    workspace.detachLeavesOfType(SIDE_PANEL_ID);
    await ((_a = workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({
      type: SIDE_PANEL_ID,
      active: true
    }));
    workspace.revealLeaf(workspace.getLeavesOfType(SIDE_PANEL_ID)[0]);
  }
  getViewType() {
    return SIDE_PANEL_ID;
  }
  getDisplayText() {
    return "ObsiDOOM";
  }
  getIcon() {
    return "swords";
  }
  async onOpen() {
    const container = this.contentEl;
    container.appendChild(this.dropDownDiv);
    container.appendChild(this.gameDiv);
    this.gameDiv.appendChild(this.generateGameIFrame());
    this.disableButton(this.openGameButton);
    container.appendChild(this.openGameButton);
    this.enableButton(this.endGameButton);
    container.appendChild(this.endGameButton);
  }
  disableButton(button) {
    if (!button.hasClass("doom-button-disabled"))
      button.addClass("doom-button-disabled");
    button.disabled = true;
  }
  enableButton(button) {
    if (button.hasClass("doom-button-disabled"))
      button.removeClass("doom-button-disabled");
    button.disabled = false;
  }
  generateGameIFrame(gameName = "DOOM") {
    const gameIFrame = document.createElement("iframe");
    gameIFrame.id = "gameIFrame";
    gameIFrame.setAttr("src", GAME_URLS[gameName]);
    gameIFrame.toggleAttribute("allowfullscreen");
    return gameIFrame;
  }
};

// src/main.ts
var ObsiDOOM = class extends import_obsidian2.Plugin {
  async onload() {
    this.addCommand({
      id: "open",
      name: "Open game",
      callback: () => SidePanel.activate(this.app.workspace)
    });
    this.registerView(SIDE_PANEL_ID, (leaf) => new SidePanel(leaf));
    this.app.workspace.onLayoutReady(() => {
      SidePanel.activate(this.app.workspace);
    });
  }
};

/* nosourcemap */